// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BoolSettingChanged(arg1:string,arg2:boolean):Promise<void>;

export function ChangeSetting(arg1:string):Promise<void>;

export function ClearLogs():Promise<void>;

export function GetSettings():Promise<string>;

export function LoadLog():Promise<void>;
