// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeSetting(arg1) {
  return window['go']['main']['App']['ChangeSetting'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function LoadLog() {
  return window['go']['main']['App']['LoadLog']();
}
